# Generated by Django 6.0.4 on 2026-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("supplier", "Supplier"),
                    ("buyer", "Buyer"),
                    ("admin", "Admin"),
                ],
                default="supplier",
                max_length=20,
            ),
        ),
    ]
