# Generated by Django 5.2.7 on 2026-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("supplier", "Supplier"),
                    ("buyer", "Buyer"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
