# Generated by Django 6.0.4 on 2026-05-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='city',
            new_name='country_region',
        ),
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='country',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='contact',
            new_name='phone_number',
        ),
    ]
