# Generated by Django 5.2.7 on 2026-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_supplierprofile_address_supplierprofile_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/suppliers/'),
        ),
    ]
