# Generated by Django 5.2.7 on 2026-05-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_supplierprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='country_region',
            new_name='country',
        ),
    ]
