# Generated by Django 6.0.4 on 2026-05-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="ton", max_length=20),
        ),
    ]
